disabled = false
languageCode = "pt-br"
languageName = "Portuguese"
weight = 1
title = ""

[params]
displayName = "PT"
isoCode = "pt-br"
rtl = false
dateFormat = "2 January 2006"
logo = "logo.png"
description = "web3 is the future"
secondaryLogo = "logo.png"
author = { image = "logo.png" }
